// react-app/src/components/LoginBadge.js
<template>
    <div className="buttons" v-if="!Session.user">
          <a className="button is-primary">
            <strong>Sign up</strong>
          </a>
          <a className="button is-light" click="login">
            Log in
          </a>
    </div>
    <div v-else>
        Hello {{name}} 
    </div>
</template>

<script>
import Session from "../services/session";

export default {
    data (){
        return ({ 
            Session
        })
    },
    methods: {
        login(){
            this.$router.push('/login');
            //this.Session.Login();

        }
    },
    computed:{
        name(){
            return this.Session.user.firstName + ' ' + this.Session.user.lastName;
        }
    }
}
</script>

<style>

</style>

// client/src/components/LoginBadge.vue
<template>
  <div class="buttons" v-if="!Session.user">
          <a class="button is-primary">
            <strong>Sign up</strong>
          </a>
          <a class="button is-light" @click="login">
            Log in
          </a>
        </div>
        <div v-else>
            Hello {{name}}
        </div>
</template>

<script>
import Session from "../services/session";


export default {
    data: ()=>{
        return ({
            Session
        })
    },
    methods: {
        login(){
            this.$router.push('/login')
            //this.Session.Login();
        }
    },
    computed:{
        name(){
            return this.user.FirstName + '' + this.user.LastName;
        }
    }
}
</script>

<style>

</style>
